### ISSUE TITLE
Support PostgreSQL as Metadata Storage

### ISSUE THREAD

**Issue by didip** [rovio/rovio-ingest#15]
Hello folks, first of all what a great project. I think this has the potential to replace native index_parallel.

We are currently evaluating this project and wondering if it can support connecting to PostgreSQL metadata store?

**Comment by juhoautio-rovio** [comment]
Thank you for the kind words.

We don't have plans for implementing support for PostgreSQL ourselves, but if anyone is willing to do it we would be glad to review a pull request and merge it.

Indeed we have also stated in [the README](https://github.com/rovio/rovio-ingest#limitations) that:

> Contributions are welcome to support other write modes or combinations of Deep Storage & Metadata Storage.

**Comment by rocel** [comment]
Hello ! 
I was about to open the same issue!
I already forked and wrote few lines, but I am wondering what would be the cleanest/best solution to configure if the user either has a MySQL DB or Postgres DB?
My quick implementation just parses DB URI specified in the configuration. What do you think ?

Also, great project! This could really replace the native ingest mechanism.

**Comment by vivek-balakrishnan-rovio** [comment]
@rocel Thanks for the kind words and interest.
About the solution, we need a factory pattern that parses the URI like you suggested to create appropriate sql connector at https://github.com/rovio/rovio-ingest/blob/main/src/main/java/com/rovio/ingest/util/MetadataUpdater.java#L78-L80


The other option, instead of parsing URI, is to introduce an enum (which the factory would use) like 
```
    enum DbType {
        Mysql,
        Postgres
        
        public static DbType from(String dbType) {
            for (DbType type : DbType.values()) {
                if (type.name().equalsIgnoreCase(dbType)) {
                    return type;
                }
            }
            
            throw new IllegalArgumentException("Unknown Dbtype " + dbType);
        }
    }
```


The enum value can be passed as a writer option like
options.put(ConfKeys.METADATA_DB_TYPE, "mysql");

I prefer the later solution. 

Hoping to see your PR :)

**Comment by rocel** [comment]
Hi @vivek-balakrishnan-rovio  thanks for the information.
Here is my [first commit using the URI parsing strategy](https://github.com/rocel/rovio-ingest/commit/614e8610a11e64adb2bd69a4e9362043f5b3c010), with a factoryMethod (`makeSqlConnector `);
Is it OK so far?

I will add the enum ASAP and propose the MR;

Also thanks for the Spark datasource PR from Druid, I did not know it, I might try it too.
